spring.application.name=heyneighbor

server.port=8081


# ============================================================
# properties after creating your Neon database.
# ============================================================

# spring.datasource.url=jdbc:postgresql://YOUR_NEON_HOST/_db?sslmode=require
# spring.datasource.username=YOUR_NEON_USERNAME
# spring.datasource.password=YOUR_NEON_PASSWORD
# spring.datasource.driver-class-name=org.postgresql.Driver

# spring.jpa.hibernate.ddl-auto=validate
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true